### ISSUE TITLE
Spread request on different task & Topics

### ISSUE THREAD

**Issue by ogomezso** [ogomezso/kafka-connect-soap#3]
In order to be able to offer the possibility of order preservation through a request we need:

- Develop a algorithm of request partition over the tasks available.
- The possibility of assign a different topic for task/request type must be configurable.

**Comment by marcelboldt** [comment]
Current state:
- dispatch of requests to tasks happens in SoapSourceConnector.taskConfigs()
- this currently happens in a round-robin fashion. If more request files than maxTasks then each taskConfig will carry multiple request files in 'requestMessageFile'. The SoapSourceTask however does not yet handle this case.

Goal:
Allow request/topic assignment strategies:
a. for a connector all requests' responses go into one topic
b. one topic per request file (create topic name from filename plus preconfigured prefix)
c. custom request/topic assignment

TODO:
- connector config properties: on how to configure which kafka topics to produce into
- SoapSourceConnector.taskConfigs(): need changes to parse the new configs and dispatch accordingly
- class SoapSourceTask: implement the behaviours described above.

**Comment by marcelboldt** [comment]
# connector config properties: determine how to configure which kafka topics to produce into

The connector config currently looks like:
```
{
  "name": "soap-country-source",
  "config": {
    "connector.class": "com.github.ogomezso.kafka.connect.soap.source.SoapSourceConnector",
    "tasks.max": 1,
    "endpointUrl": "http://wiremock:8080/mockCountries",
    "pollInterval": 5000,
    "connectionTimeOut": 3000,
    "portName": "CountriesPortSoap11",
    "requestMessageFiles": "/home/appuser/data/getCountryRequest.xml,/home/appuser/data/getAnotherCountryRequest.xml",
    "serviceName": "CountriesPortService",
    "targetNameSpace": "http://www.baeldung.com/springsoap/gen",
    "topic": "soap.test"
  }
}
```

+ add a field to select the topic assignment strategy:
"requestTopicAssignmentStrategy": <ONE_TOPIC | TOPIC_PER_REQUEST | CUSTOM_ASSIGNMENT>

+ add a field for topic prefix: "topicPrefix": STRING
  - alternative would be to use "topic" but this may cause issues with RBAC later

ONE_TOPIC:
- all responses go into the topic defined in topicPrefix + topic

TOPIC_PER_REQUEST:
topic name: topicPrefix + topic + filename

CUSTOM_ASSIGNMENT:
- for each request there must be a topic defined. #requests != #topics throws an error.
  - alternatives:
    - "topic" parameter takes a comma-separated list (topicPrefix stays single); assignment through order
    - include the topic in the requests list. (discarded)

**Comment by marcelboldt** [comment]
Done.

#2

**Comment by marcelboldt** [comment]
Merged.
